"""Initial migration

Revision ID: 29b008180a9c
Revises: 
Create Date: 2025-12-13 01:41:48.372219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29b008180a9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=256), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'PENDING', 'PROCESSING', 'FAILED', 'UNKNOWN', name='complaint_status_enum'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message')
    )
    op.create_index(op.f('ix_complaints_checksum'), 'complaints', ['checksum'], unique=False)
    op.create_index(op.f('ix_complaints_uuid'), 'complaints', ['uuid'], unique=True)
    op.create_table('complaint_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.INTEGER(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaint_responses')
    op.drop_index(op.f('ix_complaints_uuid'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_checksum'), table_name='complaints')
    op.drop_table('complaints')
    # ### end Alembic commands ###
